version: '3.3'
services:
  mssql:
    image: microsoft/mssql-server-linux:latest
    container_name: mssql-server
    ports:
      - 1433:1433
    volumes:
      - /C/data:/var/opt/mssql/data
      - ./:/docker-entrypoint-initdb.d
    working_dir: /docker-entrypoint-initdb.d
    command: sh -c 'chmod +x docker-entrypoint-initdb.sh; ./docker-entrypoint-initdb.sh & /opt/mssql/bin/sqlservr;'
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Kleopatra2019@
      COMPOSE_CONVERT_WINDOWS_PATHS: 1